import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import React from "react";
import Head from "next/head";
import Header from "@/components/head/header";
import {cookies} from "next/headers";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const cookieStore = await cookies();

  const result = await fetch(`${process.env.NEXT_PUBLIC_FRONTEND_HOST}/api/user/me`, {
    method: "GET",
    next: { revalidate: 60 },
    headers: {
      'Authorization': `Bearer ${cookieStore.get('token')?.value}`
    }
  })
  let user;
  if(result.ok) {
    const data = await result.json();
    user = data.user;
  }

  return (
    <html lang="en">
      <Head>
        <title>Game Shop - Mua bán tài khoản game uy tín</title>
        <meta name="description" content="Mua bán tài khoản game uy tín, giá rẻ" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Header user={user}/>
        {children}
      </body>
    </html>
  );
}
